print('olá, mundo')
print('tudo bem?')
print('você gosta de bolo?')
print('me chamo maria e você?')
print('atualmente estou cursando analise e desenvolvimento de sistema')
print('me chamo gaby')
print('e atualemte faço farmácia')
print('gosto muito de bolo e principalmente de chocolate e você?')
print('eu gosoto muito de bolo de prestigio')
print('tchau, foi muito bom te conhecer')